In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [2]:
number_classes = 26+10+4   #Grossbuchstaben, Zahlen, {.:/-}
anchors = [10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326]
leaky_relu_value = 0.1
number_anchors = np.size(anchors)/6
features = int(number_anchors*(4+1+number_classes))
dimension = 3
ignore_threshold = 0.7
batch_size = 1
feature_map_size_1 = 16
feature_map_size_2 = 32
feature_map_size_3 = 64


class Yolo_v3(nn.Module):
    def __init__(self):
        super(Yolo_v3, self).__init__()
        
        self.conv_1 = nn.Conv2d(dimension,32,3,stride=1,padding=1)
        self.batch_1 = nn.BatchNorm2d(32)
        
        self.conv_2 = nn.Conv2d(32,64,3,stride=2,padding=1)
        self.batch_2 = nn.BatchNorm2d(64)
        
        self.conv_3 = nn.Conv2d(64,32,1,stride=1,padding=0)
        self.batch_3 = nn.BatchNorm2d(32)
        
        self.conv_4 = nn.Conv2d(32,64,3,stride=1,padding=1)
        self.batch_4 = nn.BatchNorm2d(64)


        
        self.conv_6 = nn.Conv2d(64,128,3,stride=2,padding=1)
        self.batch_6 = nn.BatchNorm2d(128)
            
        self.conv_7 = nn.Conv2d(128,64,1,stride=1,padding=0)
        self.batch_7 = nn.BatchNorm2d(64)
        
        self.conv_8 = nn.Conv2d(64,128,3,stride=1,padding=1)
        self.batch_8 = nn.BatchNorm2d(128)
 

          
        self.conv_10 = nn.Conv2d(128,64,1,stride=1,padding=0)
        self.batch_10 = nn.BatchNorm2d(64)
        
        self.conv_11 = nn.Conv2d(64,128,3,stride=1,padding=1)
        self.batch_11 = nn.BatchNorm2d(128)
          

             
        self.conv_13 = nn.Conv2d(128,256,3,stride=2,padding=1)
        self.batch_13 = nn.BatchNorm2d(256)
        
        self.conv_14 = nn.Conv2d(256,128,1,stride=1,padding=0)
        self.batch_14 = nn.BatchNorm2d(128)
        
        self.conv_15 = nn.Conv2d(128,256,3,stride=1,padding=1)
        self.batch_15 = nn.BatchNorm2d(256)        
        


        self.conv_17 = nn.Conv2d(256,128,1,stride=1,padding=0)
        self.batch_17 = nn.BatchNorm2d(128)
        
        self.conv_18 = nn.Conv2d(128,256,3,stride=1,padding=1)
        self.batch_18 = nn.BatchNorm2d(256)
        
       
    
        
        self.conv_38 = nn.Conv2d(256,512,3,stride=2,padding=1)
        self.batch_38 = nn.BatchNorm2d(512)
        
        self.conv_39 = nn.Conv2d(512,256,1,stride=1,padding=0)
        self.batch_39 = nn.BatchNorm2d(256)
        
        self.conv_40 = nn.Conv2d(256,512,3,stride=1,padding=1)
        self.batch_40 = nn.BatchNorm2d(512)
        
        
        
        self.conv_42 = nn.Conv2d(512,256,1,stride=1,padding=0)
        self.batch_42 = nn.BatchNorm2d(256)        
        
        self.conv_43 = nn.Conv2d(256,512,3,stride=1,padding=1)
        self.batch_43 = nn.BatchNorm2d(512)
        

        
        self.conv_63 = nn.Conv2d(512,1024,3,stride=2,padding=1)
        self.batch_63 = nn.BatchNorm2d(1024)
        
        self.conv_64 = nn.Conv2d(1024,512,1,stride=1,padding=0)
        self.batch_64 = nn.BatchNorm2d(512)        
        
        self.conv_65 = nn.Conv2d(512,1024,3,stride=1,padding=1)
        self.batch_65 = nn.BatchNorm2d(1024)  
        

        
        self.conv_67 = nn.Conv2d(1024,512,1,stride=1,padding=0)
        self.batch_67 = nn.BatchNorm2d(512)
        
        self.conv_68 = nn.Conv2d(512,1024,3,stride=1,padding=1)
        self.batch_68 = nn.BatchNorm2d(1024)
        
        
        
        self.conv_76 = nn.Conv2d(1024,512,1,stride=1,padding=0)
        self.batch_76 = nn.BatchNorm2d(512)        
        
        self.conv_77 = nn.Conv2d(512,1024,3,stride=1,padding=1)
        self.batch_77 = nn.BatchNorm2d(1024)
        
        

        self.conv_82 = nn.Conv2d(1024,features,1,stride=1,padding=0)
        
        
        
        self.conv_85 = nn.Conv2d(512,256,1,stride=1,padding=0)
        self.batch_85 = nn.BatchNorm2d(256)       

        self.convT_86 = nn.ConvTranspose2d(256,256,3,stride=2,padding=1,output_padding=1)
        self.batch_86 = nn.BatchNorm2d(256) 
        
        

        self.conv_88 = nn.Conv2d(512,256,1,stride=1,padding=0)
        self.batch_88 = nn.BatchNorm2d(256)
        
        self.conv_89 = nn.Conv2d(256,512,3,stride=1,padding=1)
        self.batch_89 = nn.BatchNorm2d(512)
        
        
        
        
        self.conv_94 = nn.Conv2d(512,features,1,stride=1,padding=0)
        
        
       
        
        
        self.conv_97 = nn.Conv2d(256,128,1,stride=1,padding=0)
        self.batch_97 = nn.BatchNorm2d(128)

        self.convT_98 = nn.ConvTranspose2d(128,128,3,stride=2,padding=1,output_padding=1)
        self.batch_98 = nn.BatchNorm2d(128)
        
        
        
        self.conv_100 = nn.Conv2d(256,128,1,stride=1,padding=0)
        self.batch_100 = nn.BatchNorm2d(128)
        
        self.conv_101 = nn.Conv2d(128,256,3,stride=1,padding=1)
        self.batch_101 = nn.BatchNorm2d(256)
        
        
        
        self.conv_106 = nn.Conv2d(256,features,1,stride=1,padding=0)
        
    def forward(self, inputs):
        
        layer_1 = F.leaky_relu(self.batch_1(self.conv_1(inputs)),leaky_relu_value,True)
        layer_2 = F.leaky_relu(self.batch_2(self.conv_2(layer_1)),leaky_relu_value,True)
        layer_3 = F.leaky_relu(self.batch_3(self.conv_3(layer_2)),leaky_relu_value,True)
        layer_4 = F.leaky_relu(self.batch_4(self.conv_4(layer_3)),leaky_relu_value,True)
        layer_5 = layer_2 + layer_4
        layer_6 = F.leaky_relu(self.batch_6(self.conv_6(layer_5)),leaky_relu_value,True)
        layer_7 = F.leaky_relu(self.batch_7(self.conv_7(layer_6)),leaky_relu_value,True)
        layer_8 = F.leaky_relu(self.batch_8(self.conv_8(layer_7)),leaky_relu_value,True)
        layer_9 = layer_6 + layer_8
        layer_10 = F.leaky_relu(self.batch_10(self.conv_10(layer_9)),leaky_relu_value,True)
        layer_11 = F.leaky_relu(self.batch_11(self.conv_11(layer_10)),leaky_relu_value,True)
        layer_12 = layer_9 + layer_11
        layer_13 = F.leaky_relu(self.batch_13(self.conv_13(layer_12)),leaky_relu_value,True)
        layer_14 = F.leaky_relu(self.batch_14(self.conv_14(layer_13)),leaky_relu_value,True)
        layer_15 = F.leaky_relu(self.batch_15(self.conv_15(layer_14)),leaky_relu_value,True)
        layer_16 = layer_13 + layer_15
        layer_17 = F.leaky_relu(self.batch_17(self.conv_17(layer_16)),leaky_relu_value,True)
        layer_18 = F.leaky_relu(self.batch_18(self.conv_18(layer_17)),leaky_relu_value,True)
        layer_19 = layer_16 + layer_18      
        layer_20 = F.leaky_relu(self.batch_17(self.conv_17(layer_19)),leaky_relu_value,True)
        layer_21 = F.leaky_relu(self.batch_18(self.conv_18(layer_20)),leaky_relu_value,True)
        layer_22 = layer_19 + layer_21
        layer_23 = F.leaky_relu(self.batch_17(self.conv_17(layer_22)),leaky_relu_value,True)
        layer_24 = F.leaky_relu(self.batch_18(self.conv_18(layer_23)),leaky_relu_value,True)
        layer_25 = layer_22 + layer_24
        layer_26 = F.leaky_relu(self.batch_17(self.conv_17(layer_25)),leaky_relu_value,True)
        layer_27 = F.leaky_relu(self.batch_18(self.conv_18(layer_26)),leaky_relu_value,True)
        layer_28 = layer_25 + layer_27
        layer_29 = F.leaky_relu(self.batch_17(self.conv_17(layer_28)),leaky_relu_value,True)
        layer_30 = F.leaky_relu(self.batch_18(self.conv_18(layer_29)),leaky_relu_value,True)
        layer_31 = layer_28 + layer_30
        layer_32 = F.leaky_relu(self.batch_17(self.conv_17(layer_31)),leaky_relu_value,True)
        layer_33 = F.leaky_relu(self.batch_18(self.conv_18(layer_32)),leaky_relu_value,True)
        layer_34 = layer_31 + layer_33
        layer_35 = F.leaky_relu(self.batch_17(self.conv_17(layer_34)),leaky_relu_value,True)
        layer_36 = F.leaky_relu(self.batch_18(self.conv_18(layer_35)),leaky_relu_value,True)
        layer_37 = layer_34 + layer_36
        layer_38 = F.leaky_relu(self.batch_38(self.conv_38(layer_37)),leaky_relu_value,True)
        layer_39 = F.leaky_relu(self.batch_39(self.conv_39(layer_38)),leaky_relu_value,True)
        layer_40 = F.leaky_relu(self.batch_40(self.conv_40(layer_39)),leaky_relu_value,True)
        layer_41 = layer_38 + layer_40
        layer_42 = F.leaky_relu(self.batch_42(self.conv_42(layer_41)),leaky_relu_value,True)
        layer_43 = F.leaky_relu(self.batch_43(self.conv_43(layer_42)),leaky_relu_value,True)
        layer_44 = layer_41 + layer_43
        layer_45 = F.leaky_relu(self.batch_42(self.conv_42(layer_44)),leaky_relu_value,True)
        layer_46 = F.leaky_relu(self.batch_43(self.conv_43(layer_45)),leaky_relu_value,True)
        layer_47 = layer_44 + layer_46
        layer_48 = F.leaky_relu(self.batch_42(self.conv_42(layer_47)),leaky_relu_value,True)
        layer_49 = F.leaky_relu(self.batch_43(self.conv_43(layer_48)),leaky_relu_value,True)
        layer_50 = layer_47 + layer_49
        layer_51 = F.leaky_relu(self.batch_42(self.conv_42(layer_50)),leaky_relu_value,True)
        layer_52 = F.leaky_relu(self.batch_43(self.conv_43(layer_51)),leaky_relu_value,True)
        layer_53 = layer_50 + layer_52
        layer_54 = F.leaky_relu(self.batch_42(self.conv_42(layer_53)),leaky_relu_value,True)
        layer_55 = F.leaky_relu(self.batch_43(self.conv_43(layer_54)),leaky_relu_value,True)
        layer_56 = layer_53 +layer_55
        layer_57 = F.leaky_relu(self.batch_42(self.conv_42(layer_56)),leaky_relu_value,True)
        layer_58 = F.leaky_relu(self.batch_43(self.conv_43(layer_57)),leaky_relu_value,True)
        layer_59 = layer_56 + layer_58
        layer_60 = F.leaky_relu(self.batch_42(self.conv_42(layer_59)),leaky_relu_value,True)
        layer_61 = F.leaky_relu(self.batch_43(self.conv_43(layer_60)),leaky_relu_value,True)
        layer_62 = layer_59 + layer_61
        layer_63 = F.leaky_relu(self.batch_63(self.conv_63(layer_62)),leaky_relu_value,True)
        layer_64 = F.leaky_relu(self.batch_64(self.conv_64(layer_63)),leaky_relu_value,True)
        layer_65 = F.leaky_relu(self.batch_65(self.conv_65(layer_64)),leaky_relu_value,True)
        layer_66 = layer_63 + layer_65
        layer_67 = F.leaky_relu(self.batch_67(self.conv_67(layer_66)),leaky_relu_value,True)
        layer_68 = F.leaky_relu(self.batch_68(self.conv_68(layer_67)),leaky_relu_value,True)
        layer_69 = layer_66 + layer_68
        layer_70 = F.leaky_relu(self.batch_67(self.conv_67(layer_69)),leaky_relu_value,True)
        layer_71 = F.leaky_relu(self.batch_68(self.conv_68(layer_70)),leaky_relu_value,True)
        layer_72 = layer_69 + layer_71
        layer_73 = F.leaky_relu(self.batch_67(self.conv_67(layer_72)),leaky_relu_value,True)
        layer_74 = F.leaky_relu(self.batch_68(self.conv_68(layer_73)),leaky_relu_value,True)
        layer_75 = layer_72 + layer_74
        layer_76 = F.leaky_relu(self.batch_76(self.conv_76(layer_75)),leaky_relu_value,True)
        layer_77 = F.leaky_relu(self.batch_77(self.conv_77(layer_76)),leaky_relu_value,True)
        layer_78 = F.leaky_relu(self.batch_76(self.conv_76(layer_77)),leaky_relu_value,True)
        layer_79 = F.leaky_relu(self.batch_77(self.conv_77(layer_78)),leaky_relu_value,True)
        layer_80 = F.leaky_relu(self.batch_76(self.conv_76(layer_79)),leaky_relu_value,True)
        layer_81 = F.leaky_relu(self.batch_77(self.conv_77(layer_80)),leaky_relu_value,True)
        layer_82 = self.conv_82(layer_81)
        layer_83 = layer_82
        layer_84 = layer_80   # 16x16
        layer_85 = F.leaky_relu(self.batch_85(self.conv_85(layer_84)),leaky_relu_value,True)
        layer_86 = F.leaky_relu(self.batch_86(self.convT_86(layer_85)),leaky_relu_value,True)
        layer_87 = torch.cat((layer_60,layer_86),1)
        layer_88 = F.leaky_relu(self.batch_88(self.conv_88(layer_87)),leaky_relu_value,True)
        layer_89 = F.leaky_relu(self.batch_89(self.conv_89(layer_88)),leaky_relu_value,True)
        layer_90 = F.leaky_relu(self.batch_88(self.conv_88(layer_89)),leaky_relu_value,True)
        layer_91 = F.leaky_relu(self.batch_89(self.conv_89(layer_90)),leaky_relu_value,True)
        layer_92 = F.leaky_relu(self.batch_88(self.conv_88(layer_91)),leaky_relu_value,True)
        layer_93 = F.leaky_relu(self.batch_89(self.conv_89(layer_92)),leaky_relu_value,True)
        layer_94 = self.conv_94(layer_93)
        layer_95 = layer_94
        layer_96 = layer_92   # 32x32
        layer_97 = F.leaky_relu(self.batch_97(self.conv_97(layer_96)),leaky_relu_value,True)
        layer_98 = F.leaky_relu(self.batch_98(self.convT_98(layer_97)),leaky_relu_value,True)
        layer_99 = torch.cat((layer_35,layer_98),1)
        layer_100 = F.leaky_relu(self.batch_100(self.conv_100(layer_99)),leaky_relu_value,True)
        layer_101 = F.leaky_relu(self.batch_101(self.conv_101(layer_100)),leaky_relu_value,True)
        layer_102 = F.leaky_relu(self.batch_100(self.conv_100(layer_101)),leaky_relu_value,True)
        layer_103 = F.leaky_relu(self.batch_101(self.conv_101(layer_102)),leaky_relu_value,True)
        layer_104 = F.leaky_relu(self.batch_100(self.conv_100(layer_103)),leaky_relu_value,True)
        layer_105 = F.leaky_relu(self.batch_101(self.conv_101(layer_104)),leaky_relu_value,True)
        layer_106 = self.conv_106(layer_105)
        layer_107 = layer_106   # 64x64
        return layer_83, layer_95, layer_106   # ...*3*(5+26+10+4) = 135


In [3]:
net = Yolo_v3()
print(net)

Yolo_v3(
  (conv_1): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (batch_1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv_2): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  (batch_2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv_3): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1))
  (batch_3): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv_4): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (batch_4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv_6): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  (batch_6): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv_7): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1))
  (batch_7): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=T

In [4]:
x = torch.randn(1, 3, 512, 512)
output_layer_1, output_layer_2, output_layer_3 = net(x)
print(output_layer_1.size(),output_layer_2.size(),output_layer_3.size())

torch.Size([1, 135, 16, 16]) torch.Size([1, 135, 32, 32]) torch.Size([1, 135, 64, 64])


In [5]:
# layer_output[:,:,0,:,:] => pc
# layer_output[:,:,1,:,:] => bx
# layer_output[:,:,2,:,:] => by
# layer_output[:,:,3,:,:] => tx
# layer_output[:,:,4,:,:] => ty
# layer_output[:,:,5,:,:] => c1
# layer_output[:,:,n,:,:] => cn

In [32]:
def max_index(class_scores, ignore_threshold = 0.7):
    class_confidence = torch.cat((class_scores[:,0,:,:,:], class_scores[:,1,:,:,:], class_scores[:,2,:,:,:]),1)    # slice
    class_confidence_max, class_confidence_max_index = torch.max(class_confidence,1)   # max & max_index
    batch_size, tmp_number_classes, y, x = class_confidence.shape    # size for filter_mask 
    filter_mask = torch.zeros(batch_size, tmp_number_classes, y, x)
    for i in range(y):
        for j in range(x):
            position = class_confidence_max_index[0,i,j]
            filter_mask[0,position,i,j] = 1
            if class_confidence[0,position,i,j] < ignore_threshold:    # zero if y < ignore_threshold
                filter_mask[0,position,i,j] = 0    # set filter mask to zero if y < ignore_threshold
    return filter_mask

In [33]:
def non_max_surpression(layer_output, ignore_threshold = 0.7):
    batch_size, features, y, x = layer_output.shape   # shape for slice
    layer_output_sliced = layer_output.view(1,number_anchors,features/number_anchors,y,x)   # slice
    class_scores = torch.mul(layer_output_sliced[:,:,5:,:,:], layer_output_sliced[:,:,0:1,:,:]) # confidence * class score
    
    filter_mask = max_index(class_scores, ignore_threshold)    # only max per cell
    
    class_scores_sliced = torch.cat((class_scores[:,0,:,:,:], class_scores[:,1,:,:,:], class_scores[:,2,:,:,:]),1) # slice for mul.
    class_max = torch.mul(class_scores_sliced, filter_mask) 
    
    box_scores = torch.cat((layer_output_sliced[:,0,0:5,:,:],layer_output_sliced[:,1,0:5,:,:],layer_output_sliced[:,2,0:5,:,:]),1)
   
    
    return class_max, filter_mask, box_scores

In [40]:
a = torch.randn(1,45,3,3)
# print(a)

In [41]:
z0, z1, z2 = non_max_surpression(a,0.6)
print(z0)
print(z1)
print(z2)

tensor([[[[-0.0000, -0.0000, -0.0000],
          [ 0.0000, -0.0000,  0.0000],
          [-0.0000,  0.7790,  0.0000]],

         [[ 0.0000,  0.0000,  0.0000],
          [-0.0000, -0.0000,  0.0000],
          [ 0.0000, -0.0000,  0.0000]],

         [[ 0.0000, -0.0000, -0.0000],
          [-0.0000, -0.0000,  0.0000],
          [-0.0000,  0.0000, -0.0000]],

         [[-0.0000, -0.0000,  0.0000],
          [ 0.0000,  0.0000, -0.0000],
          [-0.0000, -0.0000, -0.0000]],

         [[-0.0000, -0.0000,  0.0000],
          [ 0.0000, -0.0000, -0.0000],
          [ 0.0000,  0.0000, -0.0000]],

         [[ 0.0000,  0.0000, -0.0000],
          [ 0.0000, -0.0000, -0.0000],
          [-0.0000, -0.0000,  0.0000]],

         [[-0.0000, -0.0000, -0.0000],
          [ 0.0000, -0.0000,  0.0000],
          [-0.0000, -0.0000, -0.0000]],

         [[ 0.0000,  0.0000,  2.3127],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]],

         [[ 0.0000, -0.0000,  0.0000],
         

In [72]:
layer_output = torch.randn(1,48,4,4)

In [73]:
batch_size, features, y, x = layer_output.shape   # shape for slice
layer_output_sliced = layer_output.view(1,number_anchors,features/number_anchors,y,x)   # slice
class_scores = torch.mul(layer_output_sliced[:,:,5:,:,:], layer_output_sliced[:,:,0:1,:,:]) # confidence * class score


batch_size, tmp_number_classes, y, x = class_confidence.shape    # size for filter_mask 
filter_mask = torch.zeros(batch_size, tmp_number_classes, y, x)




# class_confidence = torch.cat((class_scores[:,0,:,:,:], class_scores[:,1,:,:,:], class_scores[:,2,:,:,:]),1)    # slice
# class_confidence_max, class_confidence_max_index = torch.max(class_confidence,1)   # max & max_index
# batch_size, tmp_number_classes, y, x = class_confidence.shape    # size for filter_mask 
# filter_mask = torch.zeros(batch_size, tmp_number_classes, y, x)

# print('vorher:   ',class_confidence.size(),class_confidence_max.size(),class_confidence_max_index.size())

print('class_scores:   ',class_scores.size())

class_confidence_max_1, class_confidence_index_1 = torch.max(class_scores[:,0:1,:,:,:],1)
class_confidence_max_2, class_confidence_index_2 = torch.max(class_scores[:,1:2,:,:,:],1)
class_confidence_max_3, class_confidence_index_3 = torch.max(class_scores[:,2:3,:,:,:],1)
class_confidence_max = torch.cat((class_confidence_max_1, class_confidence_max_2, class_confidence_max_3),1)
class_confidence_index = torch.cat((class_confidence_index_1, class_confidence_index_2, class_confidence_index_3),1)

print('nacher:    ',class_confidence_max_1.size(), class_confidence_index_1.size())



class_scores:    torch.Size([1, 3, 11, 4, 4])
nacher:     torch.Size([1, 11, 4, 4]) torch.Size([1, 11, 4, 4])


In [75]:
print(class_confidence_max_1)

tensor([[[[ 0.2104, -0.3824,  0.4390,  0.4102],
          [ 0.9781, -1.0226,  0.3044, -0.2071],
          [ 1.2317, -0.0877,  0.3506, -0.0115],
          [-0.7000,  1.1685, -0.2327,  0.5414]],

         [[ 1.9857,  0.2910,  0.1142, -0.0463],
          [ 0.9114, -1.6743, -0.4086, -0.0605],
          [-2.7881, -0.0324,  0.2118,  0.8167],
          [ 0.4082,  1.4417,  0.7643, -0.1745]],

         [[-0.8430, -0.2323,  0.5513,  0.6136],
          [-0.2409, -1.4124,  0.0636, -0.3503],
          [ 2.5495, -0.1154,  0.1164, -0.0490],
          [-0.8633,  0.0253,  0.1555, -1.3974]],

         [[ 1.1936,  0.0451,  0.0555,  1.3909],
          [-0.3032,  0.5130, -0.9062,  0.5266],
          [ 1.7138,  0.0391,  0.0654,  0.1743],
          [ 0.5822,  0.0006, -0.2068, -1.0644]],

         [[ 0.5485,  0.1978,  0.0850, -0.9027],
          [-0.6515, -0.9149,  0.3146,  0.5290],
          [-1.6773,  0.0243,  0.3271, -0.3381],
          [ 0.4137, -1.8187, -0.9816, -1.0371]],

         [[ 1.7525,  0.0347,  

In [446]:
A = torch.randn(1,3,45,64,64)
B = A.clone()
start_time = time.time() 
A_max, A_index = torch.max(A,2,keepdim=True)
A[A<A_max] = 0
end_time = time.time()
print(end_time-start_time)
# print(A)

0.1480083465576172


In [447]:
# K = torch.rand(1,2,3,4,4)
start_time = time.time()
batch_size, number_anchors, number_classes, x, y = B.shape
K_max, K_index = torch.max(B,2)# max finden
batch = np.zeros(number_anchors*x*y) # batch bestimmen
# print('batch: ', batch.size())
x_index = np.arange(x).tolist() # tolist, weil numpy extend nicht kennt
x_index.extend(x_index*(number_anchors*x-1)) # mit extend kann mehrmals die gleiche Liste angehängt werden
# print('x_index: ', x_index)

y_index = np.repeat(np.arange(y),y,axis=0).tolist() # reapet => 0123 wird 00112233
y_index.extend(y_index*(number_anchors-1))
# print('y_index: ', y_index)


K_index_new = K_index.view(1,number_anchors*x*y)
# print('K_index_new size: ', K_index_new)

number_anchors_index = np.repeat(np.arange(number_anchors),x*y,axis=0)
# print('number_anchorse: ', number_anchors_index)


# print(K)
# print(K_index)
K_new = torch.zeros(batch_size, number_anchors, number_classes, x, y)

K_new[batch, number_anchors_index, K_index_new, np.asarray(y_index), np.asarray(x_index)] = 1 # muss array sein keine Liste => np.asarray
# print(K_new)
K_max_finish = torch.mul(K_new,A)
end_time = time.time()
print(end_time-start_time)

0.016000986099243164


In [434]:
a = np.array([1, 0, 3])
b = np.zeros((3, 4))
b[np.arange(3), a] = 1
# https://stackoverflow.com/questions/29831489/convert-array-of-indices-to-1-hot-encoded-numpy-array

In [412]:
K_max_finish = torch.mul(K_new,A)

In [413]:
print(K_max_finish)

tensor([[[[[ 0.0000,  0.9130,  0.0000,  0.0000],
           [ 0.0000,  0.0000,  0.0000,  0.0000],
           [ 0.8451,  0.0000,  0.0000,  0.1389],
           [ 0.0000,  1.5734,  0.0000,  0.0000]],

          [[ 1.0116,  0.0000,  0.0000,  0.9630],
           [ 0.0000,  0.0000,  0.0000,  0.8981],
           [ 0.0000,  0.0000,  2.3796,  0.0000],
           [ 0.0000,  0.0000,  0.5523,  0.0000]],

          [[ 0.0000,  0.0000,  1.1603,  0.0000],
           [ 0.3267,  1.2270,  0.9807,  0.0000],
           [ 0.0000,  0.2357,  0.0000,  0.0000],
           [ 0.6030,  0.0000,  0.0000,  0.3768]]],


         [[[ 0.0000,  0.0000,  0.0000,  0.0000],
           [ 0.0000,  0.8396,  0.0000, -0.0856],
           [ 0.0000,  0.0000,  0.0000,  0.0000],
           [ 0.0000, -0.1500,  0.0000,  0.0000]],

          [[ 0.0000,  0.9494,  1.0051,  0.0000],
           [ 0.7850,  0.0000,  0.7980,  0.0000],
           [ 0.0000,  0.0000, -0.0001,  0.0000],
           [ 0.4363,  0.0000,  0.0000,  0.0000]],

        

In [414]:
print(A)

tensor([[[[[ 0.0000,  0.9130,  0.0000,  0.0000],
           [ 0.0000,  0.0000,  0.0000,  0.0000],
           [ 0.8451,  0.0000,  0.0000,  0.1389],
           [ 0.0000,  1.5734,  0.0000,  0.0000]],

          [[ 1.0116,  0.0000,  0.0000,  0.9630],
           [ 0.0000,  0.0000,  0.0000,  0.8981],
           [ 0.0000,  0.0000,  2.3796,  0.0000],
           [ 0.0000,  0.0000,  0.5523,  0.0000]],

          [[ 0.0000,  0.0000,  1.1603,  0.0000],
           [ 0.3267,  1.2270,  0.9807,  0.0000],
           [ 0.0000,  0.2357,  0.0000,  0.0000],
           [ 0.6030,  0.0000,  0.0000,  0.3768]]],


         [[[ 0.0000,  0.0000,  0.0000,  0.0000],
           [ 0.0000,  0.8396,  0.0000, -0.0856],
           [ 0.0000,  0.0000,  0.0000,  0.0000],
           [ 0.0000, -0.1500,  0.0000,  0.0000]],

          [[ 0.0000,  0.9494,  1.0051,  0.0000],
           [ 0.7850,  0.0000,  0.7980,  0.0000],
           [ 0.0000,  0.0000, -0.0001,  0.0000],
           [ 0.4363,  0.0000,  0.0000,  0.0000]],

        

In [416]:
a = torch.eq(A, K_max_finish)
print(a)



tensor([[[[[ 1,  1,  1,  1],
           [ 1,  1,  1,  1],
           [ 1,  1,  1,  1],
           [ 1,  1,  1,  1]],

          [[ 1,  1,  1,  1],
           [ 1,  1,  1,  1],
           [ 1,  1,  1,  1],
           [ 1,  1,  1,  1]],

          [[ 1,  1,  1,  1],
           [ 1,  1,  1,  1],
           [ 1,  1,  1,  1],
           [ 1,  1,  1,  1]]],


         [[[ 1,  1,  1,  1],
           [ 1,  1,  1,  1],
           [ 1,  1,  1,  1],
           [ 1,  1,  1,  1]],

          [[ 1,  1,  1,  1],
           [ 1,  1,  1,  1],
           [ 1,  1,  1,  1],
           [ 1,  1,  1,  1]],

          [[ 1,  1,  1,  1],
           [ 1,  1,  1,  1],
           [ 1,  1,  1,  1],
           [ 1,  1,  1,  1]]]]], dtype=torch.uint8)


torch.float32
torch.float32
