In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [2]:
number_classes = 26+10+4   #Grossbuchstaben, Zahlen, {.:/-}
anchors = [10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326]
leaky_relu_value = 0.1
number_anchors = np.size(anchors)/6
features = int(number_anchors*(4+1+number_classes))
dimension = 3
ignore_threshold = 0.7


class Yolo_v3(nn.Module):
    def __init__(self):
        super(Yolo_v3, self).__init__()
        
        self.conv_1 = nn.Conv2d(dimension,32,3,stride=1,padding=1)
        self.batch_1 = nn.BatchNorm2d(32)
        
        self.conv_2 = nn.Conv2d(32,64,3,stride=2,padding=1)
        self.batch_2 = nn.BatchNorm2d(64)
        
        self.conv_3 = nn.Conv2d(64,32,1,stride=1,padding=0)
        self.batch_3 = nn.BatchNorm2d(32)
        
        self.conv_4 = nn.Conv2d(32,64,3,stride=1,padding=1)
        self.batch_4 = nn.BatchNorm2d(64)


        
        self.conv_6 = nn.Conv2d(64,128,3,stride=2,padding=1)
        self.batch_6 = nn.BatchNorm2d(128)
            
        self.conv_7 = nn.Conv2d(128,64,1,stride=1,padding=0)
        self.batch_7 = nn.BatchNorm2d(64)
        
        self.conv_8 = nn.Conv2d(64,128,3,stride=1,padding=1)
        self.batch_8 = nn.BatchNorm2d(128)
 

          
        self.conv_10 = nn.Conv2d(128,64,1,stride=1,padding=0)
        self.batch_10 = nn.BatchNorm2d(64)
        
        self.conv_11 = nn.Conv2d(64,128,3,stride=1,padding=1)
        self.batch_11 = nn.BatchNorm2d(128)
          

             
        self.conv_13 = nn.Conv2d(128,256,3,stride=2,padding=1)
        self.batch_13 = nn.BatchNorm2d(256)
        
        self.conv_14 = nn.Conv2d(256,128,1,stride=1,padding=0)
        self.batch_14 = nn.BatchNorm2d(128)
        
        self.conv_15 = nn.Conv2d(128,256,3,stride=1,padding=1)
        self.batch_15 = nn.BatchNorm2d(256)        
        


        self.conv_17 = nn.Conv2d(256,128,1,stride=1,padding=0)
        self.batch_17 = nn.BatchNorm2d(128)
        
        self.conv_18 = nn.Conv2d(128,256,3,stride=1,padding=1)
        self.batch_18 = nn.BatchNorm2d(256)
        
       
    
        
        self.conv_38 = nn.Conv2d(256,512,3,stride=2,padding=1)
        self.batch_38 = nn.BatchNorm2d(512)
        
        self.conv_39 = nn.Conv2d(512,256,1,stride=1,padding=0)
        self.batch_39 = nn.BatchNorm2d(256)
        
        self.conv_40 = nn.Conv2d(256,512,3,stride=1,padding=1)
        self.batch_40 = nn.BatchNorm2d(512)
        
        
        
        self.conv_42 = nn.Conv2d(512,256,1,stride=1,padding=0)
        self.batch_42 = nn.BatchNorm2d(256)        
        
        self.conv_43 = nn.Conv2d(256,512,3,stride=1,padding=1)
        self.batch_43 = nn.BatchNorm2d(512)
        

        
        self.conv_63 = nn.Conv2d(512,1024,3,stride=2,padding=1)
        self.batch_63 = nn.BatchNorm2d(1024)
        
        self.conv_64 = nn.Conv2d(1024,512,1,stride=1,padding=0)
        self.batch_64 = nn.BatchNorm2d(512)        
        
        self.conv_65 = nn.Conv2d(512,1024,3,stride=1,padding=1)
        self.batch_65 = nn.BatchNorm2d(1024)  
        

        
        self.conv_67 = nn.Conv2d(1024,512,1,stride=1,padding=0)
        self.batch_67 = nn.BatchNorm2d(512)
        
        self.conv_68 = nn.Conv2d(512,1024,3,stride=1,padding=1)
        self.batch_68 = nn.BatchNorm2d(1024)
        
        
        
        self.conv_76 = nn.Conv2d(1024,512,1,stride=1,padding=0)
        self.batch_76 = nn.BatchNorm2d(512)        
        
        self.conv_77 = nn.Conv2d(512,1024,3,stride=1,padding=1)
        self.batch_77 = nn.BatchNorm2d(1024)
        
        

        self.conv_82 = nn.Conv2d(1024,features,1,stride=1,padding=0)
        
        
        
        self.conv_85 = nn.Conv2d(512,256,1,stride=1,padding=0)
        self.batch_85 = nn.BatchNorm2d(256)       

        self.convT_86 = nn.ConvTranspose2d(256,256,3,stride=2,padding=1,output_padding=1)
        self.batch_86 = nn.BatchNorm2d(256) 
        
        

        self.conv_88 = nn.Conv2d(512,256,1,stride=1,padding=0)
        self.batch_88 = nn.BatchNorm2d(256)
        
        self.conv_89 = nn.Conv2d(256,512,3,stride=1,padding=1)
        self.batch_89 = nn.BatchNorm2d(512)
        
        
        
        
        self.conv_94 = nn.Conv2d(512,features,1,stride=1,padding=0)
        
        
       
        
        
        self.conv_97 = nn.Conv2d(256,128,1,stride=1,padding=0)
        self.batch_97 = nn.BatchNorm2d(128)

        self.convT_98 = nn.ConvTranspose2d(128,128,3,stride=2,padding=1,output_padding=1)
        self.batch_98 = nn.BatchNorm2d(128)
        
        
        
        self.conv_100 = nn.Conv2d(256,128,1,stride=1,padding=0)
        self.batch_100 = nn.BatchNorm2d(128)
        
        self.conv_101 = nn.Conv2d(128,256,3,stride=1,padding=1)
        self.batch_101 = nn.BatchNorm2d(256)
        
        
        
        self.conv_106 = nn.Conv2d(256,features,1,stride=1,padding=0)
        
    def forward(self, inputs):
        
        layer_1 = F.leaky_relu(self.batch_1(self.conv_1(inputs)),leaky_relu_value,True)
        layer_2 = F.leaky_relu(self.batch_2(self.conv_2(layer_1)),leaky_relu_value,True)
        layer_3 = F.leaky_relu(self.batch_3(self.conv_3(layer_2)),leaky_relu_value,True)
        layer_4 = F.leaky_relu(self.batch_4(self.conv_4(layer_3)),leaky_relu_value,True)
        layer_5 = layer_2 + layer_4
        layer_6 = F.leaky_relu(self.batch_6(self.conv_6(layer_5)),leaky_relu_value,True)
        layer_7 = F.leaky_relu(self.batch_7(self.conv_7(layer_6)),leaky_relu_value,True)
        layer_8 = F.leaky_relu(self.batch_8(self.conv_8(layer_7)),leaky_relu_value,True)
        layer_9 = layer_6 + layer_8
        layer_10 = F.leaky_relu(self.batch_10(self.conv_10(layer_9)),leaky_relu_value,True)
        layer_11 = F.leaky_relu(self.batch_11(self.conv_11(layer_10)),leaky_relu_value,True)
        layer_12 = layer_9 + layer_11
        layer_13 = F.leaky_relu(self.batch_13(self.conv_13(layer_12)),leaky_relu_value,True)
        layer_14 = F.leaky_relu(self.batch_14(self.conv_14(layer_13)),leaky_relu_value,True)
        layer_15 = F.leaky_relu(self.batch_15(self.conv_15(layer_14)),leaky_relu_value,True)
        layer_16 = layer_13 + layer_15
        layer_17 = F.leaky_relu(self.batch_17(self.conv_17(layer_16)),leaky_relu_value,True)
        layer_18 = F.leaky_relu(self.batch_18(self.conv_18(layer_17)),leaky_relu_value,True)
        layer_19 = layer_16 + layer_18      
        layer_20 = F.leaky_relu(self.batch_17(self.conv_17(layer_19)),leaky_relu_value,True)
        layer_21 = F.leaky_relu(self.batch_18(self.conv_18(layer_20)),leaky_relu_value,True)
        layer_22 = layer_19 + layer_21
        layer_23 = F.leaky_relu(self.batch_17(self.conv_17(layer_22)),leaky_relu_value,True)
        layer_24 = F.leaky_relu(self.batch_18(self.conv_18(layer_23)),leaky_relu_value,True)
        layer_25 = layer_22 + layer_24
        layer_26 = F.leaky_relu(self.batch_17(self.conv_17(layer_25)),leaky_relu_value,True)
        layer_27 = F.leaky_relu(self.batch_18(self.conv_18(layer_26)),leaky_relu_value,True)
        layer_28 = layer_25 + layer_27
        layer_29 = F.leaky_relu(self.batch_17(self.conv_17(layer_28)),leaky_relu_value,True)
        layer_30 = F.leaky_relu(self.batch_18(self.conv_18(layer_29)),leaky_relu_value,True)
        layer_31 = layer_28 + layer_30
        layer_32 = F.leaky_relu(self.batch_17(self.conv_17(layer_31)),leaky_relu_value,True)
        layer_33 = F.leaky_relu(self.batch_18(self.conv_18(layer_32)),leaky_relu_value,True)
        layer_34 = layer_31 + layer_33
        layer_35 = F.leaky_relu(self.batch_17(self.conv_17(layer_34)),leaky_relu_value,True)
        layer_36 = F.leaky_relu(self.batch_18(self.conv_18(layer_35)),leaky_relu_value,True)
        layer_37 = layer_34 + layer_36
        layer_38 = F.leaky_relu(self.batch_38(self.conv_38(layer_37)),leaky_relu_value,True)
        layer_39 = F.leaky_relu(self.batch_39(self.conv_39(layer_38)),leaky_relu_value,True)
        layer_40 = F.leaky_relu(self.batch_40(self.conv_40(layer_39)),leaky_relu_value,True)
        layer_41 = layer_38 + layer_40
        layer_42 = F.leaky_relu(self.batch_42(self.conv_42(layer_41)),leaky_relu_value,True)
        layer_43 = F.leaky_relu(self.batch_43(self.conv_43(layer_42)),leaky_relu_value,True)
        layer_44 = layer_41 + layer_43
        layer_45 = F.leaky_relu(self.batch_42(self.conv_42(layer_44)),leaky_relu_value,True)
        layer_46 = F.leaky_relu(self.batch_43(self.conv_43(layer_45)),leaky_relu_value,True)
        layer_47 = layer_44 + layer_46
        layer_48 = F.leaky_relu(self.batch_42(self.conv_42(layer_47)),leaky_relu_value,True)
        layer_49 = F.leaky_relu(self.batch_43(self.conv_43(layer_48)),leaky_relu_value,True)
        layer_50 = layer_47 + layer_49
        layer_51 = F.leaky_relu(self.batch_42(self.conv_42(layer_50)),leaky_relu_value,True)
        layer_52 = F.leaky_relu(self.batch_43(self.conv_43(layer_51)),leaky_relu_value,True)
        layer_53 = layer_50 + layer_52
        layer_54 = F.leaky_relu(self.batch_42(self.conv_42(layer_53)),leaky_relu_value,True)
        layer_55 = F.leaky_relu(self.batch_43(self.conv_43(layer_54)),leaky_relu_value,True)
        layer_56 = layer_53 +layer_55
        layer_57 = F.leaky_relu(self.batch_42(self.conv_42(layer_56)),leaky_relu_value,True)
        layer_58 = F.leaky_relu(self.batch_43(self.conv_43(layer_57)),leaky_relu_value,True)
        layer_59 = layer_56 + layer_58
        layer_60 = F.leaky_relu(self.batch_42(self.conv_42(layer_59)),leaky_relu_value,True)
        layer_61 = F.leaky_relu(self.batch_43(self.conv_43(layer_60)),leaky_relu_value,True)
        layer_62 = layer_59 + layer_61
        layer_63 = F.leaky_relu(self.batch_63(self.conv_63(layer_62)),leaky_relu_value,True)
        layer_64 = F.leaky_relu(self.batch_64(self.conv_64(layer_63)),leaky_relu_value,True)
        layer_65 = F.leaky_relu(self.batch_65(self.conv_65(layer_64)),leaky_relu_value,True)
        layer_66 = layer_63 + layer_65
        layer_67 = F.leaky_relu(self.batch_67(self.conv_67(layer_66)),leaky_relu_value,True)
        layer_68 = F.leaky_relu(self.batch_68(self.conv_68(layer_67)),leaky_relu_value,True)
        layer_69 = layer_66 + layer_68
        layer_70 = F.leaky_relu(self.batch_67(self.conv_67(layer_69)),leaky_relu_value,True)
        layer_71 = F.leaky_relu(self.batch_68(self.conv_68(layer_70)),leaky_relu_value,True)
        layer_72 = layer_69 + layer_71
        layer_73 = F.leaky_relu(self.batch_67(self.conv_67(layer_72)),leaky_relu_value,True)
        layer_74 = F.leaky_relu(self.batch_68(self.conv_68(layer_73)),leaky_relu_value,True)
        layer_75 = layer_72 + layer_74
        layer_76 = F.leaky_relu(self.batch_76(self.conv_76(layer_75)),leaky_relu_value,True)
        layer_77 = F.leaky_relu(self.batch_77(self.conv_77(layer_76)),leaky_relu_value,True)
        layer_78 = F.leaky_relu(self.batch_76(self.conv_76(layer_77)),leaky_relu_value,True)
        layer_79 = F.leaky_relu(self.batch_77(self.conv_77(layer_78)),leaky_relu_value,True)
        layer_80 = F.leaky_relu(self.batch_76(self.conv_76(layer_79)),leaky_relu_value,True)
        layer_81 = F.leaky_relu(self.batch_77(self.conv_77(layer_80)),leaky_relu_value,True)
        layer_82 = self.conv_82(layer_81)
        layer_83 = layer_82
        layer_84 = layer_80   # 16x16
        layer_85 = F.leaky_relu(self.batch_85(self.conv_85(layer_84)),leaky_relu_value,True)
        layer_86 = F.leaky_relu(self.batch_86(self.convT_86(layer_85)),leaky_relu_value,True)
        layer_87 = torch.cat((layer_60,layer_86),1)
        layer_88 = F.leaky_relu(self.batch_88(self.conv_88(layer_87)),leaky_relu_value,True)
        layer_89 = F.leaky_relu(self.batch_89(self.conv_89(layer_88)),leaky_relu_value,True)
        layer_90 = F.leaky_relu(self.batch_88(self.conv_88(layer_89)),leaky_relu_value,True)
        layer_91 = F.leaky_relu(self.batch_89(self.conv_89(layer_90)),leaky_relu_value,True)
        layer_92 = F.leaky_relu(self.batch_88(self.conv_88(layer_91)),leaky_relu_value,True)
        layer_93 = F.leaky_relu(self.batch_89(self.conv_89(layer_92)),leaky_relu_value,True)
        layer_94 = self.conv_94(layer_93)
        layer_95 = layer_94
        layer_96 = layer_92   # 32x32
        layer_97 = F.leaky_relu(self.batch_97(self.conv_97(layer_96)),leaky_relu_value,True)
        layer_98 = F.leaky_relu(self.batch_98(self.convT_98(layer_97)),leaky_relu_value,True)
        layer_99 = torch.cat((layer_35,layer_98),1)
        layer_100 = F.leaky_relu(self.batch_100(self.conv_100(layer_99)),leaky_relu_value,True)
        layer_101 = F.leaky_relu(self.batch_101(self.conv_101(layer_100)),leaky_relu_value,True)
        layer_102 = F.leaky_relu(self.batch_100(self.conv_100(layer_101)),leaky_relu_value,True)
        layer_103 = F.leaky_relu(self.batch_101(self.conv_101(layer_102)),leaky_relu_value,True)
        layer_104 = F.leaky_relu(self.batch_100(self.conv_100(layer_103)),leaky_relu_value,True)
        layer_105 = F.leaky_relu(self.batch_101(self.conv_101(layer_104)),leaky_relu_value,True)
        layer_106 = self.conv_106(layer_105)
        layer_107 = layer_106   # 64x64
        return layer_83, layer_95, layer_106   # ...*3*(5+26+10+4) = 135


In [3]:
net = Yolo_v3()
print(net)

Yolo_v3(
  (conv_1): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (batch_1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv_2): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  (batch_2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv_3): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1))
  (batch_3): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv_4): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (batch_4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv_6): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  (batch_6): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv_7): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1))
  (batch_7): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=T

In [4]:
x = torch.randn(1, 3, 512, 512)
output_layer_1, output_layer_2, output_layer_3 = net(x)
print(output_layer_1.size(),output_layer_2.size(),output_layer_3.size())

torch.Size([1, 135, 16, 16]) torch.Size([1, 135, 32, 32]) torch.Size([1, 135, 64, 64])


In [5]:
def output_layer_dim(output_layer):
    batch_number, outputs, y, x = output_layer.shape
    return output_layer_1.view(batch_number, number_anchors, 5, outputs/5/number_anchors, y,x)

In [6]:
print(output_layer_dim(output_layer_1).size())

torch.Size([1, 3, 5, 9, 16, 16])


In [56]:
# GRADED FUNCTION: yolo_filter_boxes

def yolo_filter_boxes(output_layer, ignore_thresh  = 0.7):
    """Filters YOLO boxes by thresholding on object and class confidence.
    
    Arguments:
    box_confidence -- tensor of shape (19, 19, 5, 1)   (1,anchor_number,1,y,x)
    boxes -- tensor of shape (19, 19, 5, 4)   (1,anchor_number,4,y,x)
    box_class_probs -- tensor of shape (19, 19, 5, 80)   (1,anchor_number,classes,y,x)
    threshold -- real value, if [ highest class probability score < threshold], then get rid of the corresponding box
    
    Returns:
    scores -- tensor of shape (None,), containing the class probability score for selected boxes
    boxes -- tensor of shape (None, 4), containing (b_x, b_y, b_h, b_w) coordinates of selected boxes
    classes -- tensor of shape (None,), containing the index of the class detected by the selected boxes
    
    Note: "None" is here because you don't know the exact number of selected boxes, as it depends on the threshold. 
    For example, the actual output size of scores would be (10,) if there are 10 boxes.
    """
    
    box_confidence = output_layer
    box_confidence[:,:,0<ingore_tresh,:,:] = 0
    
    # Step 1: Compute box scores
    ### START CODE HERE ### (≈ 1 line)
    box_scores = box_confidence[:,:,0,:,:,:] * box_class_probs[:,:,:,:,:,:] # 19x19x80   1,3,1,x,y * 1,3,
    ### END CODE HERE ###
    
    # Step 2: Find the box_classes thanks to the max box_scores, keep track of the corresponding score
    ### START CODE HERE ### (≈ 2 lines)
    box_classes = K.argmax(box_scores, axis = -1)  # 19x19x5x1  (1 class index)
    box_class_scores = K.max(box_scores, axis = -1)  # 19x19x5x1 (1 class score)
    ### END CODE HERE ###
    
    # Step 3: Create a filtering mask based on "box_class_scores" by using "threshold". The mask should have the
    # same dimension as box_class_scores, and be True for the boxes you want to keep (with probability >= threshold)
    ### START CODE HERE ### (≈ 1 line)
    filtering_mask = box_class_scores >= threshold
    ### END CODE HERE ###
    
    # Step 4: Apply the mask to scores, boxes and classes
    ### START CODE HERE ### (≈ 3 lines)
    scores = tf.boolean_mask(box_class_scores, filtering_mask)
    boxes = tf.boolean_mask(boxes, filtering_mask)
    classes = tf.boolean_mask(box_classes, filtering_mask)
    ### END CODE HERE ###
    
    return scores, boxes, classes

In [14]:
a = torch.randn(1,24)
print(a.size())
print(a)

torch.Size([1, 24])
tensor([[-0.5010,  1.3612,  0.2611,  1.1507,  0.5662,  0.8486,  1.4634,
         -0.7691,  0.6056,  1.1778,  1.2709,  0.5941, -1.3133, -3.1274,
         -0.1573, -3.1905, -1.4463, -0.5437,  0.1982, -1.0954,  0.4507,
         -1.0748,  0.3555,  1.3461]])


In [15]:
b = a.view(1,3,8)
print(b.size())
print(b)

torch.Size([1, 3, 8])
tensor([[[-0.5010,  1.3612,  0.2611,  1.1507,  0.5662,  0.8486,  1.4634,
          -0.7691],
         [ 0.6056,  1.1778,  1.2709,  0.5941, -1.3133, -3.1274, -0.1573,
          -3.1905],
         [-1.4463, -0.5437,  0.1982, -1.0954,  0.4507, -1.0748,  0.3555,
           1.3461]]])


In [16]:
a = torch.randn(1,1,12,12)
conv = nn.Conv2d(1,1,3, stride=2,padding=1)
convT = nn.ConvTranspose2d(1,1,3,stride=2,padding=0)

b = conv(a)
c = convT(b)

print("a: ", a.size())
print("b: ", b.size())
print("c: ", c.size())

a:  torch.Size([1, 1, 12, 12])
b:  torch.Size([1, 1, 6, 6])
c:  torch.Size([1, 1, 13, 13])


In [17]:
inputs = torch.randn(1, 1, 12, 12)   # Batch, Anzahl channels, X,Y 
downsample = nn.Conv2d(1, 1, 3, stride=2, padding=1)
upsample = nn.ConvTranspose2d(1, 1, 3, stride=2, padding=1,output_padding=1)
h = downsample(inputs)
print('Conv2d: ', h.size())        # (1, 1, 6, 6)
output = upsample(inputs)
print('ConvTranspose2d: ', output.size())    # (1, 1, 12, 12)
g = upsample(h)
print('Conv2d und ConvTranspose2d: ', g.size())

Conv2d:  torch.Size([1, 1, 6, 6])
ConvTranspose2d:  torch.Size([1, 1, 24, 24])
Conv2d und ConvTranspose2d:  torch.Size([1, 1, 12, 12])


In [18]:
a = torch.randn(1,3,45,16,16)
b = torch.randn(1,3,45,16,16)
a_1 = a[:,:,0:1,:,:]
b_1 = b[:,:,5:45,:,:]
print(a_1.size())
print(b_1.size())
c = a_1 * b_1
print(c.size())

torch.Size([1, 3, 1, 16, 16])
torch.Size([1, 3, 40, 16, 16])
torch.Size([1, 3, 40, 16, 16])


In [15]:
a = torch.randn(1,3,8,3,3)
print(a)

tensor([[[[[ 1.2345, -0.2779,  0.4316],
           [ 0.3223, -1.1076,  0.3231],
           [-0.2033,  1.7143,  0.4102]],

          [[ 0.5316,  2.0876,  1.4991],
           [-0.5455,  0.4920,  0.7709],
           [ 0.8501,  0.3011,  0.6388]],

          [[-1.9508, -0.6496,  1.1798],
           [ 0.4514, -1.2193,  1.2102],
           [ 1.7304, -0.9347,  0.1015]],

          [[ 0.2990, -0.8414,  0.4076],
           [-0.5978,  1.2635,  0.6946],
           [-0.0865, -0.5163, -0.9529]],

          [[-0.0847,  1.5828,  1.1811],
           [-0.5947, -1.5706, -2.2262],
           [-0.5729, -0.9777,  0.6255]],

          [[ 0.5807, -0.4617, -0.6386],
           [ 0.0175,  0.1681,  0.1788],
           [-1.6400, -0.3631, -0.0907]],

          [[-1.7215,  0.7929, -0.9163],
           [-2.4092, -1.3608,  0.2910],
           [ 0.8383,  0.2695,  1.3681]],

          [[-0.2305, -0.1474,  2.2767],
           [-0.0317,  0.3175,  0.0082],
           [ 0.3093,  0.3842,  0.0533]]],


         [[[ 0.4074,  

In [21]:
# layer_output[:,:,0,:,:] => pc
# layer_output[:,:,1,:,:] => bx
# layer_output[:,:,2,:,:] => by
# layer_output[:,:,3,:,:] => tx
# layer_output[:,:,4,:,:] => ty
# layer_output[:,:,5,:,:] => c1
# layer_output[:,:,n,:,:] => cn

In [8]:
def max_index(box_scores, ignore_threshold = 0.7):
    class_confidence = torch.cat((box_scores[:,0,:,:,:], box_scores[:,1,:,:,:], box_scores[:,2,:,:,:]),1)
    class_confidence_max, class_confidence_max_index = torch.max(class_confidence,1)
    batch_size, tmp_number_classes, y, x = class_confidence.shape
    filter_mask = torch.zeros(batch_size, tmp_number_classes, y, x)
    for i in range(y):
        for j in range(x):
            position = class_confidence_max_index[0,i,j]
            filter_mask[0,position,i,j] = 1
            if class_confidence[0,position,i,j] < ignore_threshold:
                filter_mask[0,position,i,j] = 0
    return filter_mask

In [18]:
def non_max_surpression(layer_output, ignore_threshold = 0.7):
    box_scores = torch.mul(layer_output[:,:,5:,:,:], layer_output[:,:,0,:,:]) # confidence * class score
    filter_mask = max_index(box_scores, ignore_threshold)
    # print(box_scores)
    class_max = torch.mul(box_scores, filter_mask)
    return class_max, filter_mask

In [20]:
print(ignore_threshold)
z = non_max_surpression(a,0.6)
print(z)

0.7
tensor([[[[[ 0.7169,  0.1283, -0.2757],
           [ 0.0057, -0.1862,  0.0578],
           [ 0.3333, -0.6225, -0.0372]],

          [[-0.7013,  0.1988, -1.3835],
           [ 2.0662, -0.2813,  0.2981],
           [-1.3455,  0.0282, -0.2568]],

          [[-0.0259, -0.3246, -0.5461],
           [-0.0311,  0.2887, -0.0102],
           [ 0.0055, -0.1958, -0.0276]]],


         [[[-0.5888,  0.2002, -0.0124],
           [-0.2053, -0.0851,  0.1066],
           [-0.4149,  1.8801, -0.1452]],

          [[ 0.4710,  0.1318,  0.6298],
           [-0.5452, -0.0298,  1.0229],
           [-1.2511,  0.1023,  0.0570]],

          [[ 0.1677,  1.1614,  0.0751],
           [-0.6919, -0.8823,  0.7126],
           [ 0.0157,  0.7001, -0.5836]]],


         [[[-1.7102, -0.2857,  0.7750],
           [-0.0336, -0.3453,  0.1611],
           [ 0.3339,  2.1204,  0.0067]],

          [[-0.6157,  0.0159,  0.0742],
           [-0.7470, -0.0999, -0.6704],
           [ 1.1697,  0.0879,  0.0021]],

          [[ 0.0

In [24]:
a = torch.randn(1,3,8,3,3)
b = non_max_surpression(a,0.7)
print(b.size())

torch.Size([1, 3, 3, 3, 3])


In [25]:
b = torch.mul(a[:,:,5:,:,:], a[:,:,0,:,:])
print(b.size())
# b[b<0.1] = 0
# b[b>=0.1] = 1
print(b)

torch.Size([1, 3, 3, 3, 3])
tensor([[[[[ 0.1567,  0.2116,  0.4470],
           [ 0.0388, -0.3436, -0.1389],
           [-0.2684,  0.5723,  0.8842]],

          [[-0.2455, -1.3099,  1.3137],
           [ 0.2063, -0.9575,  0.0641],
           [-0.0270, -0.1416,  0.0129]],

          [[ 0.3346,  1.7525,  1.0157],
           [-0.0269, -0.8652,  0.1784],
           [-0.9548,  0.0169, -1.0450]]],


         [[[ 0.1808,  0.0564, -0.1441],
           [-0.0912,  0.1771, -0.2231],
           [ 1.4383,  0.1073,  1.8358]],

          [[ 0.7480,  1.0265,  1.0668],
           [-0.0625, -0.9580,  0.9552],
           [-0.0056, -0.0710, -0.0329]],

          [[ 0.2037,  1.3560,  0.2751],
           [ 0.0224, -0.0567,  0.0004],
           [-0.3490, -0.5054,  0.4232]]],


         [[[-0.0508,  0.1858,  0.8422],
           [ 0.0781,  0.9442,  0.4005],
           [ 0.3027,  0.5661,  0.3054]],

          [[-0.7518,  1.2542,  0.4947],
           [ 0.0373,  0.5722,  0.2297],
           [ 0.0416, -0.0470,  0.1

In [115]:
#   box_classes = K.argmax(box_scores, axis = -1)  # 19x19x5x1  (1 class index)
#  box_class_scores = K.max(box_scores, axis = -1)  # 19x19x5x1 (1 class score)

In [8]:
a = torch.randn(1,3,8,3,3)
print(a)

tensor([[[[[ 0.1453,  0.3222, -0.8677],
           [ 0.3942, -0.8767,  0.0186],
           [-0.0429, -0.5691, -0.1548]],

          [[ 1.4984, -0.6764, -0.3858],
           [-0.1393, -0.5445, -0.3784],
           [-0.0058,  0.9321,  1.5658]],

          [[-0.0042, -0.9975,  0.1681],
           [-0.7926,  1.1236,  0.0412],
           [ 0.2972, -0.1403, -0.3645]],

          [[-0.3765, -0.8055, -0.6821],
           [-0.3558,  2.1598,  2.1103],
           [ 0.1300, -0.3741,  0.0757]],

          [[-2.5740, -0.5574, -0.7684],
           [ 1.2945, -0.0641, -0.8182],
           [-2.1312, -0.6864, -0.2527]],

          [[-0.8003,  0.7683, -1.0649],
           [ 1.8570, -0.8143, -0.5750],
           [-1.3593, -0.9354, -0.1103]],

          [[ 0.0672,  0.3824,  0.7212],
           [ 2.9575, -1.2002, -1.2147],
           [ 1.3152, -0.3910, -1.7388]],

          [[-1.1646,  0.1989,  0.9756],
           [-1.2275, -0.3666, -0.0395],
           [ 0.1581, -1.8811, -0.5720]]],


         [[[-0.6556,  

In [43]:
c = a[:,:,5:,:,:]
print(c)

tensor([[[[[-0.8149,  1.3050,  0.8988],
           [-0.0289,  0.2133, -0.4548],
           [ 0.3085, -0.9921,  0.4419]],

          [[-0.4809,  0.8808,  0.8594],
           [ 0.9602, -0.8180,  0.0453],
           [ 0.4767, -1.9962, -0.0317]],

          [[ 1.1382, -1.3587,  0.9941],
           [ 0.8660,  2.5502, -0.3065],
           [-0.4971, -0.0391, -1.3088]]],


         [[[-0.9403,  0.3480, -0.2898],
           [ 0.0680, -0.1100, -0.7302],
           [-1.6528, -0.1860,  0.9175]],

          [[ 1.4651, -0.6903,  0.6979],
           [-0.2908, -0.8185,  0.6753],
           [ 0.0986, -1.0006,  0.0808]],

          [[ 0.6930, -1.0513,  0.2692],
           [-0.7237,  0.1671, -0.0008],
           [-0.1817,  1.1708,  0.5300]]],


         [[[ 0.2645,  1.1454,  1.6934],
           [-0.0582, -0.5861,  1.3110],
           [-0.3479, -0.9814,  0.1526]],

          [[-1.4726, -0.8433,  0.3236],
           [ 0.1738,  0.4888,  0.1624],
           [-0.7360, -0.6623, -0.3939]],

          [[ 1.3607,

In [33]:
c1 = torch.cat((c[:,0,:,:,:], c[:,1,:,:,:], c[:,2,:,:,:]),1)
print(c.size())
print(c1.size())

torch.Size([1, 3, 3, 3, 3])
torch.Size([1, 9, 3, 3])


In [34]:
print(c1)

tensor([[[[-0.8149,  1.3050,  0.8988],
          [-0.0289,  0.2133, -0.4548],
          [ 0.3085, -0.9921,  0.4419]],

         [[-0.4809,  0.8808,  0.8594],
          [ 0.9602, -0.8180,  0.0453],
          [ 0.4767, -1.9962, -0.0317]],

         [[ 1.1382, -1.3587,  0.9941],
          [ 0.8660,  2.5502, -0.3065],
          [-0.4971, -0.0391, -1.3088]],

         [[-0.9403,  0.3480, -0.2898],
          [ 0.0680, -0.1100, -0.7302],
          [-1.6528, -0.1860,  0.9175]],

         [[ 1.4651, -0.6903,  0.6979],
          [-0.2908, -0.8185,  0.6753],
          [ 0.0986, -1.0006,  0.0808]],

         [[ 0.6930, -1.0513,  0.2692],
          [-0.7237,  0.1671, -0.0008],
          [-0.1817,  1.1708,  0.5300]],

         [[ 0.2645,  1.1454,  1.6934],
          [-0.0582, -0.5861,  1.3110],
          [-0.3479, -0.9814,  0.1526]],

         [[-1.4726, -0.8433,  0.3236],
          [ 0.1738,  0.4888,  0.1624],
          [-0.7360, -0.6623, -0.3939]],

         [[ 1.3607,  0.6224,  0.5630],
         