In [1]:
import numpy as np
import os
import xml.dom.minidom
import xml.etree.cElementTree as ET
import copy
from PIL import Image

In [2]:
class Place():
    place_counter = -1
    """
    Eingangsdaten:
    Klassenpfad, Ausgangsbildgrösse in px, Anzahl Bilder Channel
    
    Konstruktor genieriert ein dictonary, welches wie folgt aussieht:
    
    {Pfad_Klassen:{Klassenname_1:{0:Bildname_1, 1:Bildname1}}
                 :{Klassenname_2:{0:Bildname_1, 1:Bildname2}}
    }
    
    2 Varianten wie die einzelen Zeichen platziert werden können:
    1. rdm Verteilung
    2. ....
    
    """
    
    def __init__(self, path, size, depth):
        self._path = path
        self._size = size
        self._depth= depth
        self._dictonary = {'path':{'folder_name':{0:'image_name'}}}
        self._segmented_image = np.zeros((self._size, self._size, self._depth))
        self._bounding_boxes = np.array([0,0,0,0])
        
        path_1, dirs_1, files_1 = next(os.walk(self._path))
        self._dictonary = {path_1:{}}
        for folder in dirs_1:
            self._dictonary[path_1][folder] = {}
#             print(folder)
            path_2, dirs_2, files_2 = next(os.walk(path_1 + folder))
            for i, files in zip(range(len(files_2)), files_2):
                self._dictonary[path_1][folder][i] = {files}
#                 print(files) 

    def place(self, place_image_path):
        with Image.open(place_image_path) as image:
            img = np.array(image)
            y,x,z = img.shape
            print(y,x,z)
            
            if Place.place_counter == 0:
                

                x_max = self._size - x - 5
                y_max = self._size - y - 5
                x_rdm_min = np.random.randint(5,x_max)
                y_rdm_min = np.random.randint(5,y_max)
                x_rdm_max = x_rdm_min + x
                y_rdm_max = y_rdm_min + y
                print(x_rdm_min,y_rdm_min,x_rdm_max,y_rdm_max)
                y1,x1,z1 = segmented_image.shape
                print(y1,x1,z1)
                segmented_image[y_rdm_min:y_rdm_max,x_rdm_min:x_rdm_max ,:] = img
                
        return segmented_image, x_rdm_min,y_rdm_min,x_rdm_max,y_rdm_max    


    def get_head(self,folder,filename,path,width,height,depth):
        string_head =   '<annotation>'\
                        '<folder>'+str(folder)+'</folder>'\
                        '<filename>'+str(filename)+'</filename>'\
                        '<path>'+str(path)+'</path>'\
                        '<source>'\
                        '<database>Unknown</database>'\
                        '</source>'\
                        '<size>'\
                            '<width>'+str(width)+'</width>'\
                            '<height>'+str(height)+'</height>'\
                            '<depth>'+str(depth)+'</depth>'\
                        '</size>'\
                        '<segmented>0</segmented>'\
                        '</annotation>'
        return string_head

    def get_body(self,name,xmin,ymin,xmax,ymax):
        string_object = '<object>'\
                        '<name>'+str(name)+'</name>'\
                        '<pose>Unspecified</pose>'\
                        '<truncated>0</truncated>'\
                        '<difficult>0</difficult>'\
                        '<bndbox>'\
                            '<xmin>'+str(xmin)+'</xmin>'\
                            '<ymin>'+str(ymin)+'</ymin>'\
                            '<xmax>'+str(xmax)+'</xmax>'\
                            '<ymax>'+str(ymax)+'</ymax>'\
                            '</bndbox>'\
                        '</object>'
        return string_body
    
    
    def pretty_xml(self, string):
        dom = xml.dom.minidom.parseString(string)
        pretty_xml_as_string_body = dom.toprettyxml()
        
    
    def iou_check(self,x_rdm_min,y_rdm_min,x_rdm_max,y_rdm_max,iou_threshold):
        if self._segmentate_image.all()==0.0:
            self._bounding_boxes[0] = x_rdm_max
            self._bounding_boxes[1] = y_rdm_max
            self._bounding_boxes[2] = x_rdm_min
            self._bounding_boxes[3] = y_rdm_min
        else:
            bounding_box[0] = x_rdm_max
            bounding_box[1] = y_rdm_max
            bounding_box[2] = x_rdm_min
            bounding_box[3] = y_rdm_min
            length = len(self._bounding_boxes)/4
            for i in range(length):
                tmp_start = 0+(4*i)
                tmp_end = 3+(4*i)
                tmp_bounding_boxes = self._bounding_boxes[tmp_start:tmp_end]
                iou = bb_intersection_over_union(bounding_box, tmp_bounding_boxes)
                if iou =< iou_threshold:
                    np.append(self._bounding_boxes,bounding_boxes)
                else:
                    break
            
        ####################################################################################################################################
        ### Hier weiter machen
        
        
    def create_xml(self,dict_folder,x_rdm_min,y_rdm_min,x_rdm_max,y_rdm_max):
#         name = str(Place.placeIt_counter) + 
        if a.all()==0.0:
            xml_name = ''
            xml_name_tmp = get_body(dict_folder,x_rdm_min-1,y_rdm_min-1,x_rdm_max+1,y_rdm_max+1)
            xml_name =  xml_name + xml_name_tmp
        else:
            
            xml_name_tmp = get_body(dict_folder,x_rdm_min-1,y_rdm_min-1,x_rdm_max+1,y_rdm_max+1)
            xml_name =  xml_name + xml_name_tmp
        
       
    
    def delete_dict(self, dict_folder, dict_image): 
        del self._dictonary[self._path][dict_folder][dict_image]
        if len(list(self._dictonary[self._path][dict_folder][dict_image]))== 0:
            del self._dictonary[self._path][dict_folder]
        
        
        
        with open(image_name, "w") as file:
            file.write(image_name)


    def rdm(self):
        
        
        
        ### Zufälliger Ordner von Zeichen z.B. A oder B ###
        dict_folders = list(self._dictonary[self._path].keys())
        print(dict_folders)
        if len(dict_folders) == 0:
            number_dict_folders = 0
        else:
            number_dict_folders = np.random.randint(len(dict_folders))
        print(number_dict_folders)
        
        if number_dict_folders == 0:
            rdm_folder = 0
        else:
            rdm_folder = np.random.randint(number_dict_folders)
        print(rdm_folder)
        dict_folder = dict_folders[rdm_folder]
        print(dict_folder)
        
        ### Zufälliges Bild von oben bestimmten Zeichen ###
        dict_images = list(self._dictonary[self._path][dict_folder].keys())
        print(dict_images)
        if len(dict_images) == 0:
            number_dict_images = 0
        else:
            number_dict_images = np.random.randint(len(dict_images))
        print(number_dict_images)
        
        if number_dict_images == 0:
            rdm_image = 0
        else:
            rdm_image = np.random.randint(number_dict_images)
            
        print(rdm_image)
        dict_image_number = dict_images[rdm_image]
        dict_image = str(self._dictonary[self._path][dict_folder][dict_image_number])
        print(dict_image)
        
        r_tmp = dict_image.find('}')
        dict_image = dict_image[2:r_tmp-1]
        print(dict_image)
        
        ### Bild Pfad des Zeichens ###
        place_image_path = self._path + dict_folder + '/' +  dict_image
        Place.place_counter +=1
        
        
        segmented_image, x_rdm_min,y_rdm_min,x_rdm_max,y_rdm_max = self.place(place_image_path)
        self.create_xml(dict_folder, x_rdm_min,y_rdm_min,x_rdm_max,y_rdm_max)    
        
        
        self.delete_dict(self._path,dict_folder,dict_image)
    
        
    
    
    
    
    def bb_intersection_over_union(self, boxA, boxB):
        xA = max(boxA[0], boxB[0])
        yA = max(boxA[1], boxB[1])
        xB = min(boxA[2], boxB[2])
        yB = min(boxA[3], boxB[3])
        
        # compute the area of intersection rectangle
        interArea = max(0, xB - xA + 1) * max(0, yB - yA + 1)
        # compute the area of both the prediction and ground-truth
        # rectangles
        boxAArea = (boxA[2] - boxA[0] + 1) * (boxA[3] - boxA[1] + 1)
        boxBArea = (boxB[2] - boxB[0] + 1) * (boxB[3] - boxB[1] + 1)
        # compute the intersection over union by taking the intersection
        # area and dividing it by the sum of prediction + ground-truth
        # areas - the interesection area
        iou = interArea / float(boxAArea + boxBArea - interArea)
        # return the intersection over union value
        return iou    
    
        
        
#     def create_xml(self):    
#     def segmented_image(self):

In [3]:
obj33 = Place('C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/',512,3)

In [4]:
obj33.rdm()

['A_upperCase', 'B_upperCase']
0
0
A_upperCase
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
25
14
{'A_upperCase_DotsAllForNow_14_tailored.BMP'}
A_upperCase_DotsAllForNow_14_tailored.BMP
111 71 3
219 74 290 185
512 512 3


NameError: name 'tmp_variable' is not defined

In [5]:
for classes in list(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']):
    class_1 = list(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/'])
    number_images = len(list(list(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/'][class_1[0]])))
    if number_images != len(list(list(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/'][classes]))):
        print('Ungleichgewicht: Nicht gleichviele Bilder von jeder Klasse vorhanden, siehe Klasse: ' + classes)
        break
#     print('alles i.O')
#     print(class_1[0])
#     print(number_images)
#     print(classes)
# # len(list(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']))
# list(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/'])

Ungleichgewicht: Nicht gleichviele Bilder von jeder Klasse vorhanden, siehe KlasseB_upperCase


In [5]:
print(list(obj33._dictonary))

['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']


In [7]:
print(len(list(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']['A_upperCase'])))
del obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']['A_upperCase'][2]

2


KeyError: 2

In [8]:
print(len(list(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']['A_upperCase'])))
del obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']['A_upperCase'][1]

2


In [9]:
print(len(list(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']['A_upperCase'])))
del obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']['A_upperCase'][0]

1


In [10]:
print(len(list(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']['A_upperCase'])))

0


In [11]:
print(len(list(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/'])))
del obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']['A_upperCase']
print(len(list(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/'])))

2
1


In [12]:
print(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/'])

{'B_upperCase': {0: {'B_upperCase_arial_3_tailored.BMP'}, 1: {'B_upperCase_DotsAllForNow_4_tailored.BMP'}, 2: {'B_upperCase_MTCORSVA_5_tailored.BMP'}}}


In [6]:
list(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']['A_upperCase'])

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [25]:
a = np.zeros((9,9))
b = np.ones((3,3))
c = np.zeros((9,9))
if a.all()==0.0:
    print('juhu')
else:
    print('scheisse')
print(a)
print(b)
c[2:5,2:5] = b
print(c)
if c.all()==0.0:
    print('scheisse')
else:
    print('juhu')

juhu
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
scheisse


In [6]:
obj33.place('C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/')

PermissionError: [Errno 13] Permission denied: 'C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/'

In [5]:
print(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']['A_upperCase'][0])
a = str(obj33._dictonary['C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/']['A_upperCase'][0])
print(a.find('}'))
a[2:34]

{'A_upperCase_arial_0_tailored.BMP'}


AttributeError: 'set' object has no attribute 'find'

In [36]:
obj = Place('C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/',512,3)
print(obj._dict_images)

{'C:/Users/User/Desktop/Test/GeneratedData/TailoredImages/': {'A_upperCase': {0: {'A_upperCase_arial_020191116_191829_31.BMP'}, 1: {'A_upperCase_arial_120191116_191830_32.BMP'}, 2: {'A_upperCase_arial_220191116_191830_33.BMP'}, 3: {'A_upperCase_arial_320191116_191830_34.BMP'}, 4: {'A_upperCase_arial_420191116_191830_35.BMP'}, 5: {'A_upperCase_DotsAllForNow_020191116_191830_36.BMP'}, 6: {'A_upperCase_DotsAllForNow_120191116_191830_37.BMP'}, 7: {'A_upperCase_DotsAllForNow_220191116_191830_38.BMP'}, 8: {'A_upperCase_DotsAllForNow_320191116_191830_39.BMP'}, 9: {'A_upperCase_DotsAllForNow_420191116_191830_40.BMP'}, 10: {'A_upperCase_MTCORSVA_020191116_191831_41.BMP'}, 11: {'A_upperCase_MTCORSVA_120191116_191831_42.BMP'}, 12: {'A_upperCase_MTCORSVA_220191116_191831_43.BMP'}, 13: {'A_upperCase_MTCORSVA_320191116_191831_44.BMP'}, 14: {'A_upperCase_MTCORSVA_420191116_191831_45.BMP'}}, 'B_upperCase': {0: {'B_upperCase_arial_020191116_191831_46.BMP'}, 1: {'B_upperCase_arial_120191116_191831_47.BM

In [7]:
range(0)


  

range(0, 0)

In [1]:
print(dict_images[path_1]['A_upperCase'])
a = list(dict_images.keys())
b = list(dict_images[path_1].keys())
c = list(dict_images[path_1]['A_upperCase'].keys())
print(a)
print(b)
print(c)
print(len(c))
d = np.random.randint(len(c))
print(d)
print(dict_images[path_1]['A_upperCase'][d])

NameError: name 'dict_images' is not defined

In [2]:
a = 'aaölsfjöasf'
print(a)
a = 'ggg'
print(a)

aaölsfjöasf
ggg
