In [1]:
import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

In [2]:
# Befehl muss zweimal ausgeführt werden (komisch)
%matplotlib qt
%matplotlib qt

In [3]:
BG_COLOR = 209   ### 209
BG_SIGMA = 5 ### 5
MONOCHROME = 1   ### 1 monochrom, 3 rgb
image_size = 512

def blank_image(width=image_size, height=image_size, background=BG_COLOR):
    """
    It creates a blank image of the given background color
    """
    img = np.full((height, width, MONOCHROME), background, np.uint8)
    print('type: ', type(img))
    return img


def add_noise(img, sigma=BG_SIGMA):
    """
    Adds noise to the existing image
    """
    width, height, ch = img.shape
    n = noise(width, height, sigma=sigma)
    img = img + n
    return img.clip(0, 255)


def noise(width, height, ratio=1, sigma=BG_SIGMA):
    """
    The function generates an image, filled with gaussian nose. If ratio parameter is specified,
    noise will be generated for a lesser image and then it will be upscaled to the original size.
    In that case noise will generate larger square patterns. To avoid multiple lines, the upscale
    uses interpolation.

    :param ratio: the size of generated noise "pixels"
    :param sigma: defines bounds of noise fluctuations
    """
    mean = 0
    assert width % ratio == 0, "Can't scale image with of size {} and ratio {}".format(width, ratio)
    assert height % ratio == 0, "Can't scale image with of size {} and ratio {}".format(height, ratio)

    h = int(height / ratio)
    w = int(width / ratio)

    result = np.random.normal(mean, sigma, (w, h, MONOCHROME))
    if ratio > 1:
        result = cv2.resize(result, dsize=(width, height), interpolation=cv2.INTER_LINEAR)
    return result.reshape((width, height, MONOCHROME))


def texture(image, sigma=BG_SIGMA, turbulence=2):
    """
    Consequently applies noise patterns to the original image from big to small.

    sigma: defines bounds of noise fluctuations
    turbulence: defines how quickly big patterns will be replaced with the small ones. The lower
    value - the more iterations will be performed during texture generation.
    """
    result = image.astype(float)
    cols, rows, ch = image.shape
    ratio = cols
    while not ratio == 1:
        result += noise(cols, rows, ratio, sigma=sigma)
        ratio = (ratio // turbulence) or 1
    cut = np.clip(result, 0, 255)
    return cut.astype(np.uint8)


if __name__ == '__main__':
    
    a = blank_image(background=230)
    b = texture(a, sigma = 4, turbulence=4)
    y,x,z = b.shape
    print(y,x,z)
    if z == 1:
        image_rgb =  np.zeros((y,x,3))
        y,x,z = image_rgb.shape
        texture_image = texture(blank_image(background=230), sigma=4, turbulence=4)
        texture_and_noise_image = add_noise(texture(blank_image(background=230), sigma=4), sigma=10)
        noise_image = add_noise(blank_image(image_size, image_size), sigma=10)
        image_rgb[:,:,0] = texture_and_noise_image[:,:,0].astype(int)
        image_rgb[:,:,1] = texture_and_noise_image[:,:,0].astype(int)     
        image_rgb[:,:,2] = texture_and_noise_image[:,:,0].astype(int)      
        print(image_rgb[:,:,1])
        
        img_uint8 = Image.fromarray(np.uint8(image_rgb))
        img_uint8.save('C:/Users/User/Desktop/Test/'+'texture_and_noise_image'+'.bmp')
        
# with Image.open('C:/Users/User/Desktop/Test/'+'texture_and_noise_image'+'.bmp') as file:
#     a = np.array()

#         cv2.imwrite('texture.bmp', texture(blank_image(background=230), sigma=4, turbulence=4))
#         cv2.imwrite('texture-and-noise.bmp', add_noise(texture(blank_image(background=230), sigma=4), sigma=10))
#         cv2.imwrite('noise.bmp', add_noise(blank_image(image_size, image_size), sigma=10))

type:  <class 'numpy.ndarray'>
512 512 1
type:  <class 'numpy.ndarray'>
type:  <class 'numpy.ndarray'>
type:  <class 'numpy.ndarray'>
[[217. 203. 221. ... 211. 209. 206.]
 [246. 228. 209. ... 223. 211. 214.]
 [236. 216. 229. ... 210. 204. 206.]
 ...
 [201. 198. 196. ... 242. 203. 243.]
 [177. 217. 205. ... 228. 213. 238.]
 [205. 184. 194. ... 218. 244. 229.]]


In [72]:
# print(a)
# print(b)
print(type(b))
c = np.array(b)
print(type(c))
img_uint8 = Image.fromarray(c)
img_uint8.save('C:/Users/User/Desktop/Test/' + 'new'+'.bmp')

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


TypeError: Cannot handle this data type

In [48]:
with Image.open('C:/Users/User/Desktop/Test/20191201_202353_14_8_12_11.bmp') as binary_image:
    with Image.open('C:/Users/User/Desktop/Test/texture_and_noise_image.bmp') as texture_noise:
        scale = 0.30
        binary_image = np.array(binary_image)
        texture_noise = np.array(texture_noise)
        final_image = np.add(scale*binary_image/255,texture_noise/255)
        plt.figure('adf')
        plt.imshow(binary_image)
        plt.figure('adsf')
        plt.imshow(texture_noise)
        plt.figure('final')
        plt.imshow(final_image)
        image_max = np.max(final_image)
        img_uint8 = Image.fromarray(np.uint8(final_image/image_max*255))
        img_uint8.save('C:/Users/User/Desktop/Test/'+'final_image'+ '_' + str(scale)+'.bmp')
        print('C:/Users/User/Desktop/Test/'+'final_image'+ '_' + str(scale)+'.bmp')
#         print(type(binary_image))
#         print(type(texture_noise))
#         print(binary_image)
#         final_image = np.add(binary_image,texture_noise)
#         plt.figure('final_image')
#         plt.imshow(final_image)
#         img_uint8 = Image.fromarray(np.uint8(final_image))
#         img_uint8.save('C:/Users/User/Desktop/Test/ '+'final_image'+'.bmp')

Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


C:/Users/User/Desktop/Test/final_image_0.3.bmp


## Sinuskurve 

In [9]:


a = np.zeros((512,512,3))
b = np.zeros((512,512,3))

### a ###
min_grayValue_1 = 10
max_grayValue_1 = 255
shift_1 = -np.pi/2
image_size_1 = 512
frequency_1 = 1

### b ###
min_grayValue_2 = 10
max_grayValue_2 = 255
shift_2 = -np.pi/2
image_size_2 = 512
frequency_2 = 1


for i in range(512):
    for j in range(512):
        a[i,j,:] = ((np.sin(2*np.pi/image_size_1*frequency_1*i+shift_1))+1)/2*(max_grayValue_1-min_grayValue_1)+min_grayValue_1
        b[i,j,:] = ((np.sin(2*np.pi/image_size_2*frequency_2*j+shift_2))+1)/2*(max_grayValue_2-min_grayValue_2)+min_grayValue_2
#         if i == 0:
# #             print(a[0,j,0])
                
plt.figure('a')
plt.imshow(a/255)

plt.figure('b')
plt.imshow(b/255)


c = (a/2+b/2)
plt.figure('c')
plt.imshow(c/255)

In [17]:
c = np.zeros((25,256,3))
for i in range(256):
    c[:,i,:] = i
    plt.figure('gerade')
    plt.imshow(c/255)

In [16]:
b = np.empty((512,512))
for i in range(512*30):
    tmp_x = np.random.randint(0,512)
    tmp_y = np.random.randint(0,512)
    tmp_value = np.random.randint(255)
    b[tmp_y,tmp_x] = tmp_value
plt.figure('asdfasdf')
plt.imshow(b/255)

In [65]:
array = b

In [70]:
import numpy as np
from scipy import interpolate
x = np.arange(0, array.shape[1])
y = np.arange(0, array.shape[0])
#mask invalid values
array = np.ma.masked_invalid(array)
xx, yy = np.meshgrid(x, y)
#get only the valid values
x1 = xx[~array.mask]
y1 = yy[~array.mask]
newarr = array[~array.mask]

GD1 = interpolate.griddata((x1, y1), newarr.ravel(),(xx, yy),method='cubic')

print(GD1)
print(type(GD1))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
<class 'numpy.ndarray'>


In [72]:
d = np.zeros((512,512,3))
d[:,:,0] = GD1
d[:,:,1] = GD1
d[:,:,2] = GD1
plt.figure('qewr')
plt.imshow(d/255)

## Color Generator

In [90]:
for m in range(1000):
    tolerance = 10
    size = 64
    C = np.zeros((size,size,3))
    probability = np.random.randint(0,101)
    if probability >= 30:
        r = np.random.randint(16,240)
        g = np.random.randint(r-tolerance,r+tolerance)
        b = np.random.randint(r-tolerance,r+tolerance)
    else:
        r = np.random.randint(16,240)
        g = np.random.randint(16,240)
        b = np.random.randint(16,240)
    for i in range(size):
        for j in range(size):
            tolerance_field = 10
            C[i,j,0] = np.random.randint(r-tolerance_field,r+tolerance_field)
            C[i,j,1] = np.random.randint(g-tolerance_field,g+tolerance_field)
            C[i,j,2] = np.random.randint(b-tolerance_field,b+tolerance_field)
            # plt.figure('A')
            # plt.imshow(A/255)
    im2 = Image.fromarray(np.uint8(C))
    im2.save('C:/Users/User/Desktop/Test/PossibleBackgrounds/TEST_randomColorCharacters/'+'C'+str(m)+'.bmp')


In [83]:
for m in range(100):
    size = 128
    A = np.zeros((size,size,3))
    B = np.zeros((size,size,3))
    r = np.random.randint(16,235)
    g = np.random.randint(16,235)
    b = np.random.randint(16,235)


    for i in range(size):
        for j in range(size):
            tolerance = 10
            tolerance_gaussian = int(tolerance*0.67)
            A[i,j,0] = np.random.randint(r-tolerance,r+tolerance)
            A[i,j,1] = np.random.randint(g-tolerance,g+tolerance)
            A[i,j,2] = np.random.randint(b-tolerance,b+tolerance)
    # plt.figure('A')
    # plt.imshow(A/255)
    im1 = Image.fromarray(np.uint8(A))
    im1.save('C:/Users/User/Desktop/Test/PossibleBackgrounds/TEST_randomColorCharacters/'+'A'+str(m)+'.bmp')


    a = np.random.normal(r,tolerance_gaussian,size*size).astype(int)
    b = np.random.normal(g,tolerance_gaussian,size*size).astype(int)
    c = np.random.normal(b,tolerance_gaussian,size*size).astype(int)
    a = a.reshape(size,size)
    b = b.reshape(size,size)
    c = c.reshape(size,size)
    B[:,:,0] = a
    B[:,:,1] = b
    B[:,:,2] = c
    # B = np.concatenate(B,c)
    y,x,z = B.shape
    im = Image.fromarray(np.uint8(B))
    im.save('C:/Users/User/Desktop/Test/PossibleBackgrounds/TEST_randomColorCharacters/'+'B'+str(m)+'.bmp')

    # print(y,x,z)
    # plt.figure('B')
    # plt.imshow(B/255)
    


Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


512 512 3


In [31]:
import matplotlib.colors as c
hsv_matrix = np.zeros((1,1,3))
h_vector = np.random.normal(250,10,(1,1))
s_vector = np.random.normal(60,10,(1,1))
v_vector = np.random.normal(60,10,(1,1))
h_vector[h_vector>360] = 360
h_vector[h_vector<0] = 0
s_vector[s_vector>100] = 100
s_vector[s_vector<0] = 0
v_vector[v_vector>100] = 100
v_vector[v_vector<0] = 0
print(h_vector,s_vector,v_vector)
h_vector = h_vector/360
s_vector = s_vector/100
v_vector = v_vector/100
hsv_matrix[:,:,0] = h_vector
hsv_matrix[:,:,1] = s_vector
hsv_matrix[:,:,2] = v_vector
b = c.hsv_to_rgb(hsv_matrix)*255
b = b.astype(int)
print(b)

[[237.37067131]] [[56.10575298]] [[55.98473843]]
[[[ 62  66 142]]]
